INSERT INTO USER (EMAIL, PHONE_NUM, SIGN_DATE, USER_NAME, USER_PW) values ('admin@admin.com', '01000000000', '2021-07-18', 'admin', '$2a$10$BRa9xoKaRCZRdF4wN1E7JOUpaQCLDKrNzJ0sduWnb7BuLjN9fW/i6');
INSERT INTO USER (EMAIL, PHONE_NUM, SIGN_DATE, USER_NAME, USER_PW) values ('test@test.com', '01000000001', '2021-07-17', 'test', '$2a$10$wesf1N2Lbme8eokPsJoDEeZ0nJ.JbJQxuCYvmPsfUmESHbUIPs6gK');

INSERT INTO USER_ROLE (ROLE_NAME) values ('ROLE_USER');
INSERT INTO USER_ROLE (ROLE_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (EMAIL, ROLE_NAME) values ('admin@admin.com', 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (EMAIL, ROLE_NAME) values ('test@test.com', 'ROLE_USER');